"""Generate immutable logo outlines from the OFL Literata font.

python3 scripts/outline-wordmark.py /path/to/Literata.ttf
Requires fontTools. Font sources and licenses: vendor/fonts/README.md.
"""
import json
import sys
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen


def outline(font, text, box, tracking=0):
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    path = SVGPathPen(glyphs, ntos=lambda n: str(round(n, 2)))
    bounds = BoundsPen(glyphs)
    x = 0
    for char in text:
        glyph = glyphs[cmap[ord(char)]]
        for pen in [path, bounds]:
            glyph.draw(TransformPen(pen, (1, 0, 0, -1, x, 0)))
        x += glyph.width + tracking
    left, top, right, bottom = bounds.bounds
    bx, by, width, height = box
    sx, sy = width / (right - left), height / (bottom - top)
    transform = f'matrix({sx:.8f} 0 0 {sy:.8f} {bx-left*sx:.8f} {by-top*sy:.8f})'
    return f'<path transform="{transform}" d="{path.getCommands()}"/>'


literata = instantiateVariableFont(TTFont(sys.argv[1]), {'opsz': 36, 'wght': 650})
# Fixed glyph bounds from the supplied 1169 × 1142 reference.
glyph_boxes = [
    ('B', (29, 310, 221, 253)), ('i', (251, 304, 87, 259)), ('g', (340, 366, 184, 280)),
    ('F', (28, 618, 210, 249)), ('e', (218, 686, 165, 186)), ('e', (387, 686, 158, 186)),
    ('l', (545, 603, 90, 264)), ('i', (640, 604, 87, 263)), ('n', (728, 680, 192, 187)),
    ('g', (913, 665, 183, 281)),
]
lines = [
    '<g id="logo-lettering" aria-label="Big Feeling">',
    '<g fill="#062627">',
    *[outline(literata, glyph, box) for glyph, box in glyph_boxes],
    '</g></g>',
]
destination = Path(__file__).resolve().parents[1] / 'src/logo-wordmark.js'
destination.write_text('// Generated by scripts/outline-wordmark.py; font licenses in vendor/fonts/.\n'
                       + 'export const WORDMARK = ' + json.dumps('\n'.join(lines)) + ';\n')
